/**
 * 全局事件名字定义
 */
export enum GlobalEvent {
  /** 拖拽方块组合x坐标调整完毕 */
  Cube_ADJUST_DONE,
  DRAG_ADJUST_DONE,
  /** 方块组合拖拽中 */
  CUBE_BOX_DRAGING,
  CUBE_BOX_DRAG_INDEX,
  CUBE_BOX_DRAG_CANCEL,
  CUBE_BOX_PLACE_DONE,
  CUBE_BOX_SET_STATE_DONE,
  GAME_START,
  GAME_RESTART,
  EAT_COL,
  EAT_ROW,
  KILL_DIRECTLY,
  UPDATE_SCORE,
  UPDATE_COMBO,
  GAME_OVER,
  ON_KILL,
  ROW_EFFECT,
  COL_EFFECT,
  SHOW_TEXT,
  UPDATE_PRE_SCORE,
  SHOW_OVER_LAYER,
  CLEAR_CUBE_ROOT,
  PREPARE_CUBE_BG,
  PLAY_RAINBOW_EFFECT,
  UPDATE_RAINBOW_SCORE,

  // 音效
  PLAY_KILL_EFFECT,
  PLAY_30_BGM,
  PLAY_LETSGO,
  PLAY_BIU,
  PLAY_TOUCH,
  PLAY_PLACE,
  PLAY_TEXT,
  PLAY_SCORE,
  PLAY_OVER,
  PLAY_SPECIAL_A,
  PLAY_SPECIAL_B,
  PLAY_OVER_NO_PLACE,
  PLAY_OVER_TIME_UP,
  PLAY_OVER_TAB,
  PLAY_LAY_FAIL,
  PLAY_SPECIAL_B_BGM,
  PLAY_SPECIAL_A_BGM
}
